# Generated by Django 5.1.7 on 2025-03-14 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Favorite",
            fields=[
                ("f_id", models.AutoField(primary_key=True, serialize=False)),
                ("user_id", models.CharField(max_length=255)),
                ("show_id", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "favorite",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Show",
            fields=[
                ("s_id", models.AutoField(primary_key=True, serialize=False)),
                ("s_name", models.CharField(max_length=255)),
                ("actor", models.CharField(max_length=255)),
                ("picture", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("date", models.DateField()),
                ("address", models.CharField(max_length=255)),
                ("genre", models.CharField(blank=True, max_length=255, null=True)),
                ("link", models.URLField(blank=True, null=True)),
            ],
            options={
                "db_table": "show_info",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=255, unique=True)),
                ("password", models.CharField(max_length=1024)),
                ("role", models.CharField(default="user", max_length=255)),
            ],
            options={
                "db_table": "users",
                "managed": True,
            },
        ),
    ]
